# Generated by Django 5.1.7 on 2025-10-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('team_leader', models.CharField(max_length=100)),
                ('members', models.TextField(help_text='Comma separated names of team members')),
            ],
        ),
    ]
