# Generated by Django 5.1.7 on 2025-10-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employeedirecting_remove_task_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='machines',
            field=models.TextField(blank=True, help_text='Comma separated machines'),
        ),
        migrations.AddField(
            model_name='team',
            name='materials',
            field=models.TextField(blank=True, help_text='Comma separated materials'),
        ),
    ]
